# Generated by Django 4.1.1 on 2022-10-01 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Create',
            new_name='Blog',
        ),
    ]
