# Generated by Django 4.1.1 on 2022-10-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_blog_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='owner',
            field=models.CharField(max_length=100, verbose_name='Owner'),
        ),
    ]
