# Generated by Django 4.1.1 on 2022-10-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_blog_share_alter_blog_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(help_text='Description...', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(help_text='Title...', max_length=50, verbose_name='Title'),
        ),
    ]
